### ISSUE TITLE
NuGet Package only available for .NetConsoleApp

### ISSUE THREAD

**Issue by pstather** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#25]
Hi,
Do you know why the NuGet package for this is only available for the .NetCoreApp and not .netstandard?

Thanks

**Comment by AntonyVorontsov** [comment]
Hi!

The latest version of the library (which is v3.1.1) targets .Net Core 3.1 platform and the project has been targeted different .Net Core versions for the whole process of its development. But I am finalizing the release v3.1.2 version which will be targeting the netstandard 2.1. So this is the reason why you can see the netstandard2.1 in the .csproj file, but can't use the previous version in the netstandard project.

Just wait a couple of days for the new version and you will be good to go!

Best regards,
Antony

**Comment by AntonyVorontsov** [comment]
I have just released a library version that targets .netstandard2.1, you can find it in NuGet and try it out!

**Comment by pstather** [comment]
Fantastic, thank you.
