### ISSUE TITLE
Update library to NetStandard 2.2

### ISSUE THREAD

**Issue by mjendza** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#26]
Is there a chance to update library to net standard 2.2 ? https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/blob/master/src/RabbitMQ.Client.Core.DependencyInjection/RabbitMQ.Client.Core.DependencyInjection.csproj#L4

**Comment by AntonyVorontsov** [comment]
Hi mjendza,

As far as I know there is no such version of netstandard. The 2.1 version is the latest, and you can see it [here](https://github.com/dotnet/standard/blob/master/docs/versions.md).

The dotnet team actually has plans to come up with something new considering that [milestone](https://github.com/dotnet/standard/milestone/4) will be finished. Thus, netstandard2.1 is the newest platform that can be targeted right now (taking into the account that netcoreapp3.1 can easily use netstandard2.1 libs).

Best regards,
Antony

**Comment by mjendza** [comment]
Yes, sorry I haven't checked the versions, wanted to use you package with Asp.Net Core 2.2, swichted to 3.0 :)

THX
