### ISSUE TITLE
Unacked messages on consuming!

### ISSUE THREAD

**Issue by ussamoo** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#32]
The Library throw an Exception (Exception thrown: 'RabbitMQ.Client.Exceptions.AlreadyClosedException') and messages are unakced.

The project samples throw the exception below on messages consuming:

![image](https://user-images.githubusercontent.com/8547025/77832930-c925e580-7139-11ea-8332-43a6fffdde33.png)

**Comment by AntonyVorontsov** [comment]
Thanks man.
I will make a new patch release ASAP.

**Comment by ussamoo** [comment]
Sorry ! I didn't check the unit tests because i thought they weren't impacted by my small change.

**Comment by AntonyVorontsov** [comment]
I drafted a new release.
It is right here https://www.nuget.org/packages/RabbitMQ.Client.Core.DependencyInjection/3.2.1

Thanks again! This bug was kind a mess
