### ISSUE TITLE
Examples.BatchMessageHandler

### ISSUE THREAD

**Issue by goranhell** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#46]
doesn't work

**Comment by AntonyVorontsov** [comment]
Hi, Göran

Can you please provide a little bit more information?
It will be cool If you can show me a code sample which doest not work, thus, I can reproduce the issue/issues.

Either it works, but something is unclear in the documentation.

Best regards,
Antony

**Comment by goranhell** [comment]
![bild](https://user-images.githubusercontent.com/14040520/83187927-36042e80-a12f-11ea-98fd-2291a488df07.png)
I get this. The code it untouched.

**Comment by AntonyVorontsov** [comment]
I have just drafted a new release 4.1.1. Try it out. The problem was kinda silly - there were connection factory DI registering missed 🛑 

Try it out.

**Comment by goranhell** [comment]
Seems to work, thx
