### ISSUE TITLE
Make it possible to read Message Headers inside Consumer Handlers

### ISSUE THREAD

**Issue by astaffer** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#49]
I have different message types in one queue with single routing key.  The **message headers** have additional information about the type of message. So I want to read **message headers** inside Handle method in Consumer Handler but for now its not possible it has only string message and routing key.

What do you think?

**Comment by JanEggers** [comment]
I would also prefere if the handlers would take the raw eventargs from the native client.

**Comment by AntonyVorontsov** [comment]
I have just made a slight change and I will draft a new release v4.3.0 soon.
Keep in mind that those changes will break your current code.

I've covered that in changelog https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/blob/master/docs/changelog.md#changed and docs https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/blob/master/docs/message-consumption.md#synchronous-message-handlers

Best regards,
Antony
