### ISSUE TITLE
netframework compatibility

### ISSUE THREAD

**Issue by JanEggers** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#50]
Hi there,

I want to use your libraray but I have an existing app in netframework.

Do you have any obligations downgrading to netstandard2.0 so this is possible?

Im willing to try that out / create a pr.

**Comment by AntonyVorontsov** [comment]
I don't think this is a case since netstandard won't be supported in featuring versions. Moreover, this lib uses a net core DI mechanism so I don't see a proper usage of this inside a framework project.

But well. I have already closed an initial PR.

**Comment by JanEggers** [comment]
FYI @AntonyVorontsov we forked your project and have it working with netframework. but we also had to downgrade some nugets to get it it working. I dont think its worth to port back since its just a steppingstone while migrating to netcore.
