### ISSUE TITLE
Nuget update

### ISSUE THREAD

**Issue by MrMihap** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#53]
Is it possible to update nuget puckage with latest commit? (which implements retries for failed messages)
I am planning to use this library in a project based on microservices and sagas. This feature is important for the implementation of the architecture patterns.

**Comment by AntonyVorontsov** [comment]
Yeah, not a problem.

I am sorry with late answers, was as busy as a beaver and I am going to get back to the project development.
I will add a newest version of this library along with solution of https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/issues/48

Just wait a couple more days. WIP

**Comment by AntonyVorontsov** [comment]
Drafted a new release v4.2.0.

Have a good time using it!
