### ISSUE TITLE
refactor IProducingService

### ISSUE THREAD

**Issue by JanEggers** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#59]
currently IProducingService is quite large and contains a lot of send overloads.

I would prefere if the is just one send method in the interface and the other methods should be replaced by extension methods / default interface implementations

**Comment by AntonyVorontsov** [comment]
Same as in previous issue.

It will be reworked right here https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/pull/73

Thank you for your contribution!
