### ISSUE TITLE
Starting client in QueueService constructor

### ISSUE THREAD

**Issue by andrejt** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#61]
Isn't that a bit early and uncontrollable? If server is unavailable, the whole app might be blocking, even before logging is set up, so app could just crash without any information. Which may be a wanted effect, but I'd prefer keeping this more under control by moving StartClient() to a later stage, e.g. before StartConsuming(), or maybe even a separate method, exposed through IQueueService?

**Comment by fbridger** [comment]
We are experiencing this specific issue and getting a `InitialConnectionException`. 

If the connection to RabbitMQ cannot be establish the entire Application fails because the Depedency cannot be injected.

**Comment by fbridger** [comment]
I was able to solve this by injecting a Lazy loaded dependency

StartUp
```c#
var rabbitMqSection = configuration.GetSection("rabbitMq");
var exchangeOptions = new RabbitMqExchangeOptions
{
    Type = "fanout",
    Durable = true
};

services.AddRabbitMqProducingClientSingleton(rabbitMqSection)
    .AddProductionExchange("exchange", exchangeOptions);

// Allow to inject Lazy loaded instance for IProducingService
services.AddScoped(x => new Lazy<IProducingService>(() => x.GetRequiredService<IProducingService>()));
```

Implementation
```c#
public class EventPublisher
{
    private readonly Lazy<IProducingService> _producingService;

    public EventPublisher(Lazy<IProducingService> producingService)
    {
        _producingService = producingService;
    }

    public async Task PublishEvent()
    {
        await _producingService.Value.SendAsync(
            @object: new { Message = "something",
            exchangeName: "exchange",
            routingKey: "my.key");
    }
}
```

**Comment by AntonyVorontsov** [comment]
@andrejt I am so late to answer that issue, but better later than never, right?

I'll start with a small story how this library even appeared. Some time ago I'd had to deal with rabbitMQ in one of my projects at work and I decided to create a small library that would help me with queue declarations and other stuff. I came up with simple idea to make a single `QueueService` that would be responsible for all the work: both consumption and production of messages. That was a **huge mistake**. Simplicity took over common programming principles as single responsibility.
Same thing for declarations in constructor - simplicity is the key.

Then I posted this library at GitHub and NuGet without a hope that it will be useful to someone, but after people began to use it I started trying to avoid making breaking changes. And yeah, it is a **mistake** as well, coz I have to do it anyway.

There is an [issue](https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/issues/72) where I share my thoughts about reworking current paradigm of `QueueService`, and here is a [pull request](https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/pull/73) where you can track upcoming changes.
I hope a new library version will come up in a week or so.

I think that it answers initial question, so I intend to close this issue. Feel free to re-open it if something is not clear and if the pull-request and connected issue do not satisfy your desires.

**Comment by AntonyVorontsov** [comment]
@fbridger I am happy you solved that problem by yourself!

Please take a look at this [issue](https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/issues/72) and the [pull request](https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/pull/73) too.

After an update that can change the way you use the library.

And if you have a suggestion (or a couple of them) feel free to leave them in the "Upcoming changes issue"
