### ISSUE TITLE
copy and paste error in dispose

### ISSUE THREAD

**Issue by JanEggers** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#62]
https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/blob/b021237baef07e110bd7b66d47b581832c55f602/src/RabbitMQ.Client.Core.DependencyInjection/Services/QueueService.cs#L79

this should be consumingconnection i guess

**Comment by AntonyVorontsov** [comment]
Yup. Thank you, Jan.

I'll fix it right here https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/pull/73
