### ISSUE TITLE
More than one RabbitMq broker?

### ISSUE THREAD

**Issue by iamkinetic** [AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection#66]
Is there anyway to use this library when we need to use more than one RabbitMq broker within the same application?

**Comment by AntonyVorontsov** [comment]
@iamkinetic I am sorry for the long response.

You can configure multiple hosts with multiple endpoints like [this](https://github.com/AntonyVorontsov/RabbitMQ.Client.Core.DependencyInjection/blob/master/docs/rabbit-configuration.md#multiple-nodes-configuration)

Best regards,
Antony

**Comment by AntonyVorontsov** [comment]
I will close this issue, but feel free to reopen it if something is unclear.
